name: Publish Unity SDK on NuGet

on: [ workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8

      - name: Pack NuGet package
        shell: pwsh
        working-directory: Unity/NuGet
        run: ./pack.ps1

      - name: Push NuGet package
        uses: edumserrano/nuget-push@v1.2.2
        with:
          api-key: ${{ secrets.NUGET_API_KEY }}
          working-directory: Unity/NuGet/bin/Release
